export const subscriptionIconMap: Record<string, string> = {
  // Streaming
  netflix: 'netflix',
  youtube: 'youtube',
  'youtube premium': 'youtube',
  'yt premium': 'youtube',
  'prime video': 'primevideo',
  'amazon prime': 'primevideo',
  hotstar: 'hotstar',
  'disney+ hotstar': 'hotstar',
  disney: 'disney',
  'disney+': 'disney',
  hbo: 'hbo',
  'hbo max': 'hbo',
  hulu: 'hulu',
  'sony liv': 'sonyliv',
  sonyliv: 'sonyliv',
  zee5: 'zee5',
  zee: 'zee5',
  'jio cinema': 'jiocinema',
  jiocinema: 'jiocinema',
  crunchyroll: 'crunchyroll',
  
  // Music
  spotify: 'spotify',
  'apple music': 'applemusic',
  'jio saavn': 'jiosaavn',
  jiosaavn: 'jiosaavn',
  saavn: 'jiosaavn',
  gaana: 'gaana',
  wynk: 'wynk',
  audible: 'audible',
  
  // AI
  chatgpt: 'chatgpt',
  openai: 'chatgpt',
  gpt: 'chatgpt',
  claude: 'claude',
  anthropic: 'claude',
  gemini: 'gemini',
  google: 'google',
  copilot: 'copilot',
  
  // Dev & Productivity
  github: 'github',
  notion: 'notion',
  figma: 'figma',
  adobe: 'adobe',
  'creative cloud': 'adobe',
  dropbox: 'dropbox',
  canva: 'canva',
  grammarly: 'grammarly',
  slack: 'slack',
  zoom: 'zoom',
  discord: 'discord',
  twitch: 'twitch',
  linkedin: 'linkedin',
  
  // Gaming
  playstation: 'playstation',
  'ps plus': 'playstation',
  'ps5': 'playstation',
  xbox: 'xbox',
  'game pass': 'xbox',
  steam: 'steam',
  nintendo: 'nintendo',
  'epic games': 'epicgames',
  epic: 'epicgames',
  
  // Cloud & Tech
  amazon: 'amazon',
  'google one': 'googleone',
  'google drive': 'googleone',
  microsoft: 'microsoft',
  'office 365': 'microsoft',
  'microsoft 365': 'microsoft',
  onedrive: 'microsoft',
  m365: 'microsoft',
  aws: 'aws',
  'amazon web services': 'aws',
  vercel: 'vercel',
  cloudflare: 'cloudflare',
  'digital ocean': 'digitalocean',
  digitalocean: 'digitalocean',
  
  // Security
  '1password': 'onepassword',
  'one password': 'onepassword',
  lastpass: 'lastpass',
  bitwarden: 'bitwarden',
  nordvpn: 'nordvpn',
  'nord vpn': 'nordvpn',
  expressvpn: 'expressvpn',
  'express vpn': 'expressvpn',
  surfshark: 'surfshark',
  'proton vpn': 'protonvpn',
  protonvpn: 'protonvpn',
  
  // Education
  duolingo: 'duolingo',
  coursera: 'coursera',
  udemy: 'udemy',
  
  // Indian Telecom
  jio: 'jio',
  'reliance jio': 'jio',
  airtel: 'airtel',
  vi: 'vi',
  vodafone: 'vi',
  'vodafone idea': 'vi',
  bsnl: 'bsnl',
  
  // Indian Services
  swiggy: 'swiggy',
  'swiggy one': 'swiggy',
  zomato: 'zomato',
  'zomato pro': 'zomato',
  'zomato gold': 'zomato',
  'times prime': 'timesprime',
};
